name: Constructions Updater
on:
  workflow_dispatch:
    inputs: {}
jobs:
  download:
    name: Download json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download constructions json
        run: |
          curl -L -o assets/constructions.json ${{ secrets.CONSTRUCTIONS_API_ENDPOINT }}
      - name: Run formatting
        run: yarn format
      - name: Push json file
        run: |
          git remote set-url origin https://github-actions:${{ github.token }}@github.com/${{ github.repository }}
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add assets/constructions.json
          git commit -m "🏢 Update constructions.json"
          git push origin HEAD:${{ github.ref }}
